Add two methods to extend existing errors.Fields by new keys
nordcloud/ncerrors pull request #4
Opened 2020-04-02 10:47 UTC by jkrajniak

Two new methods on `errors.Fields`:
  - `Add(key, val)` : adds a single item to existing `Fields` and return a new `Fields` instance
 - `Extend(Fields)`: similar, but extend existing `Fields` with provided `Fields`, as well returns new `Fields` instance

In both methods the existing keys can be overwritten.

Example:

```go

func handler(param string) {
 // some global error fields
  errorFields := errors.Fields{"param": param}
  ...
  if err := someOtherFunction(param2); err != nil {
    return errors.WithContext(err, "failed to call other function" , errorFields.Add("param2", param2))
  }
}

```

2020-04-02 10:51 UTC, kevwargo approved these changes

2020-04-15 07:21 UTC, piotrszumny requested changes
It would be nice to add information about overriding the keys in the comments.

2020-04-15 07:21 UTC, piotrszumny commented on errors/error.go
> +//Add adds key:val to the Fields, returns copy
```suggestion
// Add adds key:val to the Fields, returns copy.
```

2020-04-15 07:21 UTC, piotrszumny commented on errors/error.go
> +//Extend extends Fields with the content of extFields, returns copy
```suggestion
// Extend extends Fields with the content of extFields, returns copy.
```

2020-04-15 07:21 UTC, piotrszumny commented on errors/error.go
> +func (f Fields) copy() Fields {
Since this function is unexported it can be moved below the exported ones.

2020-04-15 07:21 UTC, piotrszumny commented on errors/error.go
>  // Cause keeps the context information about the error
```suggestion
// Cause keeps the context information about the error.
```

2020-04-15 07:21 UTC, piotrszumny commented on errors/error_test.go
> +func TestFieldsAdd(t *testing.T) {
What do you think about this one:
```
fields := Fields{"key1": "val1", "key2": "val2"}
extFields := fields.Add("key3", "val3")
expectedFields := Fields{"key1": "val1", "key2": "val2", "key3":"val3"}
assert.Equal(t, expectedFields, extFields)
```
It seems to be more readable and it checks whether the fields were extended with the key without changing/removing the original ones.

2020-04-15 07:21 UTC, piotrszumny commented on errors/error_test.go
> +	assert.Equal(t, nil, fields["key3"])
Probably we don't have to check that we do not change the `fields` ancestor's state, not sure tho.

2020-04-15 07:21 UTC, piotrszumny commented on errors/error_test.go
> +func TestFieldsExtend(t *testing.T) {
IMO same as above :thinking:

2020-04-15 07:21 UTC, piotrszumny commented on errors/error.go
> +	newFields := make(map[string]interface{})
We can specifiy hashmap length since we know it initially 
```suggestion
	newFields := make(map[string]interface{}, len(f))
```

2020-04-15 09:38 UTC, tdi approved these changes

2020-04-22 11:36 UTC, piotrszumny commented on errors/error_test.go
> +	// Check if
Is there missing something in the comment? :thinking:

2020-04-22 11:38 UTC, piotrszumny approved these changes

2020-04-22 16:04 UTC, merged